# Safety policy file
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        37504:
            reason: Fixed Twine version requires Python>=3.6 and is used there
        38330:
            reason: Fixed Sphinx version requires Python>=3.5 and is used there
        39611:
            reason: PyYAML full_load method or FullLoader is not used
        39621:
            reason: Fixed Pylint version requires Python>=3.6 and is used there
        40291:
            reason: Pip, found in;10.0.1, affected; <19.2, Fixed Pip version requires Python>=3.6 and is used there
        42559:
            reason: Fixed Pip version requires Python>=3.6 and is used there; Pip is not shipped with this package
        43975:
            reason: Fixed Urllib3 versions are excluded by requests
        45185:
            reason: Fixed Pylint version requires Python>=3.6.2 and is used there
        45775:
            reason: Fixed Sphinx version requires Python>=3.5 and is used there
        47833:
            reason: Fixed Click version requires Python>=3.6 and is used there
        50885:
            reason: Fixed Pygments version requires Python>=3.5 and is used there
        50886:
            reason: Fixed Pygments version requires Python>=3.5 and is used there
        51457:
            reason: Py package is no longer being fixed (latest version 1.11.0)
        51499:
            reason: Fixed Wheel version requires Python>=3.7 and is used there; Risk is on Pypi side
        52322:
            reason: Fixed GitPython version requires Python>=3.7 and is used there
        52365:
            reason: Fixed Certifi version requires Python>=3.6 and is used there
        52495:
            reason: Fixed Setuptools version requires Python>=3.7 and is used there; Risk is on Pypi side
        52518:
            reason: Fixed GitPython version requires Python>=3.7 and is used there
        38765:
            reason: Pip, found in; 10.0.1, affected; <19.2, Python 2.7 requires this version
        37765:
            reason: Psutil, found in; 5.6.5, affected; <=5.6.5,
        51358:
            reason: Safety, found in; 1.8.7, affected; <2.2.0,
        50571:
            reason: Dparse, found in; 0.4.1, affected; <0.5.2,
        42203:
            reason: Babel, found in; 2.7.0, affected; <2.9.1
        52510:
            reason: Future, found in; 0.18.2; affected; <=0.18.2
        39525:
            reason: Jinja2, found in; 2.8.1, affected; <2.11.3
        54679:
            reason: Jinja2, found in; 2.8.1, affected; <2.10.1
        58755:
            reason: Fixed requests version 2.31.0 requires Python>=3.7 and is used there
        58910:
            reason: Fixed pygments version 2.15.0 requires Python>=3.7 and is used there
        59071:
            reason: Fixed tornado version 6.3.2 requires Python>=3.8 and is used there
        59062:
            reason: Fixed cryptography version 41.0.0 requires Python>=3.7 and is used there
        39252:
            reason: Fixed cryptography version 3.3 requires Python 2.7 or Python>=3.6 and is used there
        59956:
            reason: Fixed certifi version 2023.07.22 requires Python>=3.6 and is used there
        59910:
            reason: Fixed sphinx version 3.3.0 requires Python>=3.5 and is used there
        59925:
            reason: Fixed sphinx version 3.3.0 requires Python>=3.5 and is used there
        60350:
            reason: GitPython, Python 2.7, 3.6. fixed version 3.1.32 requires Python>=3.7
        60789:
            reason: GitPython, Python 2.7, 3.6. fixed version 3.1.33 requires Python>=3.7
        60841:
            reason: GitPython, Python 2.7, 3.6. fixed version 3.1.35 requires Python>=3.7
        61949:
            reason: Fixed tornado version 6.3.3 requires Python>=3.8 and is used there
        62044:
            reason: Fixed pip version 23.3 requires Python>=3.7 and is used there

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
