# Safety policy file for packages needed for installation
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        37765:
            reason: Psutil, found in; 5.6.5, affected; <=5.6.5,
        39611:
            reason: PyYAML full_load method or FullLoader is not used
        40291:
            reason: Pip, found in;10.0.1, affected; <19.2, Fixed Pip version requires Python>=3.6 and is used there
        42559:
            reason: Fixed Pip version requires Python>=3.6 and is used there; Pip is not shipped with this package
        47833:
            reason: Fixed Click version requires Python>=3.6 and is used there
        51499:
            reason: Fixed Wheel version requires Python>=3.7 and is used there; Risk is on Pypi side
        52365:
            reason: Fixed Certifi version requires Python>=3.6 and is used there
        52495:
            reason: Fixed Setuptools version requires Python>=3.7 and is used there; Risk is on Pypi side
        58755:
            reason: Fixed requests version 2.31.0 requires Python>=3.7 and is used there
        59956:
            reason: Fixed certifi version 2023.07.22 requires Python>=3.6 and is used there
        62044:
            reason: Fixed pip version 23.3 requires Python>=3.7 and is used there
        62817:
            reason: Fixed prompt-toolkit version 3.0.13 requires Python>=3.6 and is used there
        67599:
            reason: There is no fixed pip version
        67895:
            reason: Fixed idna version 3.7 requires requests>=2.26.0 which requires Python>=3.6 and is used there
        71064:
            reason: Fixed requests version 2.32.2 requires Python>=3.8 and is used there
        71608:
            reason: Fixed urllib3 version 2.2.2 requires Python>=3.8 and is used there
        72236:
            reason: Fixed setuptools version 70.0.0 requires Python>=3.8 and is used there
        75180:
            reason: Fixed pip version 25.0 requires Python>=3.8 and is used there
        76752:
            reason: Fixed setuptools version 78.1.1 requires Python>=3.9 and pyproject.toml does not support python_version markers
        77680:
            reason: Fixed requests version 2.32.4 requires Python>=3.8 and is used there
        77744:
            reason: Fixed urllib3 version 2.5.0 requires Python>=3.9 and is used there
        77745:
            reason: Fixed urllib3 version 2.5.0 requires Python>=3.9 and is used there
        79883:
            reason: Fixed pip version 25.2 requires Python>=3.9 and is used there

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
