# Safety policy file
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        37504:
            reason: Fixed Twine version requires Python>=3.6 and is used there
        38330:
            reason: Fixed Sphinx version requires Python>=3.5 and is used there
        39525:
            reason: Jinja2, found in; 2.8.1, affected; <2.11.3
        42203:
            reason: Babel, found in; 2.7.0, affected; <2.9.1
        45185:
            reason: Fixed Pylint version requires Python>=3.6.2 and is used there
        45775:
            reason: Fixed Sphinx version requires Python>=3.5 and is used there
        50571:
            reason: Dparse, found in; 0.4.1, affected; <0.5.2,
        50885:
            reason: Fixed Pygments version requires Python>=3.5 and is used there
        50886:
            reason: Fixed Pygments version requires Python>=3.5 and is used there
        51358:
            reason: Safety, found in; 1.8.7, affected; <2.2.0,
        51457:
            reason: Py package is no longer being fixed (latest version 1.11.0)
        52322:
            reason: Fixed GitPython version requires Python>=3.7 and is used there
        52518:
            reason: Fixed GitPython version requires Python>=3.7 and is used there
        54679:
            reason: Jinja2, found in; 2.8.1, affected; <2.10.1
        58910:
            reason: Fixed pygments version 2.15.0 requires Python>=3.7 and is used there
        59071:
            reason: Fixed tornado version 6.3.2 requires Python>=3.8 and is used there
        59910:
            reason: Fixed sphinx version 3.3.0 requires Python>=3.5 and is used there
        59925:
            reason: Fixed sphinx version 3.3.0 requires Python>=3.5 and is used there
        60350:
            reason: GitPython, Python 2.7, 3.6. fixed version 3.1.32 requires Python>=3.7
        60789:
            reason: GitPython, Python 2.7, 3.6. fixed version 3.1.33 requires Python>=3.7
        60841:
            reason: GitPython, Python 2.7, 3.6. fixed version 3.1.35 requires Python>=3.7
        61949:
            reason: Fixed tornado version 6.3.3 requires Python>=3.8 and is used there
        63687:
            reason: Fixed GitPython version 3.1.41 requires Python>=3.7 and is used there
        64227:
            reason: Fixed Jinja2 version 3.1.3 requires Python>=3.7 and is used on Python>=3.10
        65581:
            reason: Fixed tornado version 6.3.3 requires Python>=3.8 and is used there
        68477:
            reason: Fixed virtualenv version 20.21.0 requires Python>=3.7 and is used there
        70612:
            reason: Safety issue and CVE do not list a fixed version of Jinja2
        70790:
            reason: Fixed tqdm version 4.66.3 requires Python>=3.7 and is used there
        71591:
            reason: Fixed Jinja2 version 3.1.4 requires Python>=3.7 and is used there
        71636:
            reason: Fixed authlib version 1.3.1 requires Python>=3.8 and is used there
        71956:
            reason: Fixed tornado version 6.4.1 requires Python>=3.8 and is used there
        71957:
            reason: Fixed tornado version 6.4.0 requires Python>=3.8 and is used there
        72083:
            reason: Fixed certifi version 2024.07.04 requires Python>=3.6 and is used there
        72132:
            reason: Fixed zipp version 3.19.1 requires Python>=3.8 and is used there
        73456:
            reason: Fixed virtualenv version 20.26.6 requires Python>=3.12 and is used there
        74439:
            reason: Fixed tornado version 6.4.2 requires Python>=3.8 and is used there
        74735:
            reason: Fixed jinja2 version 3.1.5 requires Python>=3.7 and is used there
        75976:
            reason: Fixed jinja2 version 3.1.6 requires Python>=3.7 and is used there
        76378:
            reason: Fixed jinja2 version 3.1.5 requires Python>=3.7 and is used there
        77319:
            reason: Fixed tornado version 6.5.0 requires Python>=3.9 and is used there
        78825:
            reason: Fixed virtualenv version 20.26.6 requires Python>=3.7 and is used there
        79756:
            reason: Fixed authlib version 1.6.4 requires Python>=3.9 and is used there
        80401:
            reason: Fixed authlib version 1.6.5 requires Python>=3.9 and is used there
        81132:
            reason: Fixed authlib version 1.6.5 requires Python>=3.9 and is used there

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
